config/routes.rb
Video1::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products

  resources :products do
  collection { post :import }
end

  root :to => "home#index"
  get "home" => "home#index"
  
get 'product/Signs'
get 'product/Products'

get 'signs/regulatory'
get 'traffic_product/traffic_product'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  #dodao
 attr_accessible :title, :category, :image_url, :shape, :code
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
	csv << product.attributes.values_at(*column_names)
      end
    end
  end
  #dodao
  
#radi IMPORT klasican
  def self.to_csv(options ={} )
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
	csv << product.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
    product = find_by_id(row["id"]) || new
    product.attributes = row.to_hash.slice(*accessible_attributes)
    product.save!
    end
  end
  
  ###############
  #za upload odkomentarisati ovo dole a zakomentarisati ovo
  #iznad
  
#def self.import(file)
#  spreadsheet = open_spreadsheet(file)
#  header = spreadsheet.row(1)
#  (2..spreadsheet.last_row).each do |i|
#    row = Hash[[header, spreadsheet.row(i)].transpose]
#    product = find_by_id(row["id"]) || new
    #product.attributes = row.to_hash.slice(*accessible_attributes) OVO NE
#    product.save!
#  end
#end

#def self.open_spreadsheet(file)
#  case File.extname(file.original_filename)
#  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
#  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
#  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
#  else raise "Unknown file type: #{file.original_filename}"
#  end
#end




  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def Signs
  end

  def Products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    #dodao
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls #{send_data @products.to_csv(col_sep: "\t")}
    end
  end

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Products Imported!"
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :category, :image_url, :shape, :code)
    end
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  def regulatory
  end

end

app/controllers/traffic_product_controller.rb
class TrafficProductController < ApplicationController
  def traffic_product
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/helpers/traffic_product_helper.rb
module TrafficProductHelper
end

app/views/home/index.html.erb
<center><h3>Signal d.o.o</h3></center>


<%= link_to 'Add Signs', product_Signs_path %>
</br>
</br>
<%= link_to 'Add Products', product_Products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product/Products.html.erb
<h3>Traffic Control Products</h3>

<%= link_to 'Traffic Control devices', traffic_product_traffic_product_path %>

app/views/product/Signs.html.erb
<h3>Traffic Signs</h3>


<%= link_to "Regulatory Sings", products_path %>
</br></br>
<%= link_to_function "Back", "history.back()" %>
</br></br>
<%= link_to "Home", home_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :shape %><br>
    <%= f.text_field :shape %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<script type="text/javascript">
/*Dropdown Load from MYSQL INTO RAILS*/
    $(function(){
      $('#id').bind('change', function () {
         var url = "/products/" + $(this).val()
          if (url) {
              window.location.replace(url);
          }
          return false;
      });
    });
</script>
<script type="text/javascript">
/*DISABLED RIGHT CLICK*/
document.onmousedown=disableclick;
status="Right Click Disabled";
Function disableclick(event)
{
  if(event.button==2)
   {
     alert(status);
     return false;    
   }
}
</script>

<h1>Regulatorni znaci!</h1>

<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %> |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>

<table>
  <tbody oncontextmenu="return false">
    <% @products.each do |product| %>
      <tr class='<%= cycle('list_line_odd', 'list_line_even') %>'>
        <td><%= image_tag(product.image_url, class: 'list_image',
:size=>"80x80") %></td>
        <td class="list_description">
        <dl>
        <dt><%= product. title %></dt>
        <dd><%= truncate(strip_tags(product.category), length:80) %></dd>
        </dl>
        </td>
        <td><%= product.shape %></td>
        
        <td class="list_actions">
        <%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm:
'Are you sure?' } %>
      </td>      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= select_tag 'id',options_from_collection_for_select(@products, "id", "title") %>



</br></br></br>


<h2>Upload Products</h2>

<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<%= link_to 'New Product', new_product_path %>
</br></br>
<%= link_to "Home", home_path %>
</br>
</br>
<%= link_to_function "Back", "history.back()" %>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
	<Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.title %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.shape %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.category %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> title:</strong>
  <%= @product. title %>
</p>

<p>
  <strong>category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>shape:</strong>
  <%= @product.shape %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/traffic_product/traffic_product.html.erb
radi traffic_product strana
</br>
<%= link_to "Home", home_path %>
</br>
<%= link_to_function "Back", "history.back()" %>